name: ecommerce_pipeline
version: "1.0.0"
config-version: 2
profile: ecommerce_pipeline

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

clean-targets: ["target", "dbt_packages"]

models:
  ecommerce_pipeline:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
